<?= view('site/partials/header', get_defined_vars()) ?>
<?= view('site/partials/navbar', get_defined_vars()) ?>
<div class="inner_banner-section bg-light-2">
      <div class="container">
        <div class="inner_banner-content-block">
          <h3 class="inner_banner-title">TERMS OF SERVICE</h3>
          <ul class="banner__page-navigator">
            <li>
              <a href="<?php echo $MY_CURRENT_PATH; ?>">Home</a>
            </li>
            <li class="active">
              <a href="#">
                TERMS OF SERVICE
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <section class="section-padding-120">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p class="mb-4">Last Updated: 4/2/2026</p>

                    <p class="mb-4 text-justify">These Terms of Use (“Terms of Use”) apply to all services, information and opportunities offered by, and any transactions with safecreditscore.com, its past, present, or future parents, subsidiaries, affiliates, predecessors, assignees, successors, and their respective agents, employees, directors, officers, partners, and members (whether acting in their corporate or individual capacity) (“safecreditscore.com”, “we” “our” or “us”). A complete list of safecreditscore.com partner websites is available <a href="#">here</a>. Notwithstanding any language in the Terms of Use to the contrary, the Terms of Use have the same effect as an agreement in writing and govern your use of any of our technologies and platforms, including this website, safecreditscore.com and its content or any safecreditscore.com mobile application (collectively the “Website”), your engagement of our services (as defined below, the “Services”), and/or your request that we contact you about its Services.</p>

                    <h4 class="mb-4 text-justify" style="font-weight: 700;">BY USING THE WEBSITE AND THE SERVICES AND/OR REQUESTING THAT WE CONTACT YOU ABOUT OUR SERVICES, YOU AGREE TO THESE TERMS OF USE AND AGREE TO COMPLY WITH ALL APPLICABLE LAWS AND REGULATIONS. IF YOU DO NOT AGREE TO THESE TERMS OF USE, YOU MAY NOT ACCESS OR OTHERWISE USE THE WEBSITE OR SERVICES OR ANY INFORMATION CONTAINED ON THIS WEBSITE. WE RESERVE THE RIGHT TO MODIFY OR AMEND THESE TERMS OF USE FROM TIME TO TIME WITHOUT NOTICE. YOUR CONTINUED USE OF THE WEBSITE AND SERVICES FOLLOWING THE CHANGES TO THESE TERMS OF USE WILL MEAN YOU ACCEPT THOSE CHANGES.</h4>

                    <p class="mb-4 text-justify">You are responsible for regularly reviewing the Terms of Use, by clicking on the “Terms of Use” link on the Website. The Terms of Use may be supplemented by additional terms and conditions applicable to privacy, specific areas of the Website, or to where particular content or transactions are posted in particular areas of the Website and, together with the Terms of Use, shall govern your use of those areas, content, or transactions.</p>

                    <h2 class="mb-4" style="font-weight: 700;">INFORMATIONAL PURPOSES; NO PROFESSIONAL ADVICE.</h2>

                    <p class="mb-4 text-justify">THE INFORMATION, CONTENT AND MATERIALS CONTAINED AT AND WITHIN THE WEBSITE IS PROVIDED FOR INFORMATIONAL AND EDUCATIONAL PURPOSES ONLY. IT IS NOT MEANT TO BE A SUBSTITUTE FOR PROFESSIONAL COUNSELING AND/OR ADVICE FROM CERTIFIED LEGAL OR FINANCIAL PROFESSIONALS. FOR SPECIFIC ADVICE REGARDING YOUR PARTICULAR SITUATION, YOU MUST SEEK ADVICE FROM QUALIFIED LEGAL, TAX OR FINANCIAL ADVISORS.</p>

                    <p class="mb-4 text-justify">We are not a credit repair organization, credit counselor, or financial or legal advisor as defined under federal or state law. Use of our Services is not a replacement for personal, professional advice or assistance regarding your finances, credit history or fixing your credit rating. Additionally, we do not guarantee that the information we present as part of our Services, including credit report or credit score information, is the same information that may be used or reviewed by a third party to assess your creditworthiness or eligibility for any particular product or service or for employment. We do not represent or guarantee the accuracy or reliability of any advice, opinion, statement, or other information displayed or distributed through the Website. You acknowledge that any reliance upon any such information shall be at your sole risk. We reserve the right, in our sole discretion, to correct any errors or omissions in any portion of the Website. Any information contained on the Website with respect to results obtained is not meant to indicate that the same or similar results can or will be obtained in other cases or situations. Results will vary depending on the facts and circumstances of each individual matter. Prior results do not predict, warrant or guarantee a similar outcome. References to past or present members or the circumstances of their specific matters do not constitute testimonials or endorsements by such members, nor are they a guarantee, warranty or prediction of the outcome of your matter.</p>

                    <p class="mb-4 text-justify">We do not guarantee that the information we present as part of the Services, including credit report or credit score information, is the same information that may be used or reviewed by a third party to assess your creditworthiness, eligibility for any particular product or service, or for employment. We do not represent or guarantee the accuracy or reliability of any advice, opinion, statement, or other information displayed or distributed through the Services. You acknowledge that any reliance upon any such information shall be at your sole risk.</p>

                    <h2 class="mb-4" style="font-weight: 700;">SERVICES.</h2>

                    <p class="mb-4 text-justify">The Website markets to and provides users of the Website with general educational and informational resources about the Services, and the ability to register for the Services. "Services" shall mean all products, services and member benefits provided on or accessed through the Website, including the content, features, tools, data, software and functions made available by or through the Website. You are not required to sign up for our Services in order to visit and read material on the Website, however, you will need to register in order to use and take advantage of the Services. Services may be provided by one or more third-party service providers and you may be subject to additional and separate terms, conditions and policies as required by such service providers or as set forth on the service provider websites.</p>

                    <p class="mb-4 text-justify">Products and Services offered include the following:</p>

                    <p class="mb-4 text-justify"><strong style="text-decoration: underline;">My Credit Manager.</strong> The My Credit Manager product offering is available as part of the Services and includes access to your VantageScore® 3.0 credit score and credit monitoring from one or more of the credit bureaus with alerts that may affect your credit. The My Credit Manager product offering, including all content, data, and information, may be used for credit education purposes only, except to the extent you provide consent for such content, data, and information to be used for another permissible purpose. Like other credit scores offered to consumers, the credit score that we offer may not be the same score used by a lender or other commercial users for credit decisions. Credit monitoring monitors the credit file most closely identified with you based on multiple identifying factors such as first, middle and last names, current and former addresses, Social Security number and date of birth. If it is believed that the consumer data or reports may be inaccurate or missing information, your sole remedy is to contact the applicable credit bureau that is providing and reporting such inaccuracies or missing information.</p>

                    <p class="mb-4 text-justify"><strong style="text-decoration: underline;">Identity Protect.</strong> The Identity Protect product offering is available as part of the Services and includes monitoring online activity (dark web monitoring) for protection against identity theft (including change of address and social security number monitoring) and fraud prevention. It also includes identity insurance and restoration services designed to help you protect your identity (up to $1,000,000 in value). Subject to certain limitations and restrictions. See the Summary of Identity Protection Reimbursement Coverage terms here. The Identity Protect product offering, including all content, data and information, may be used for education and identity protection purposes only and for no other purpose, except to the extent you provide consent for such content, data, and information to be used for another permissible purpose.</p>

                    <p class="mb-4 text-justify"><strong style="text-decoration: underline;">Personal Info Protection.</strong> The Personal Info Protection product offering is available as part of the Services and allows you to view and remove certain personal information that has been published by third parties on certain data broker websites. You understand and agree that we are not responsible for the actions or inactions of any of the data broker websites, and safecreditscore.com makes no representations, warranties, or guarantees related to such data broker websites. You expressly agree that safecreditscore.com will not be liable to you under any circumstances for any actions or inactions of third-party data brokers and/or such data broker websites, or safecreditscore.com's failure for any reason to exercise effective opt-outs on your behalf.</p>

                    <p class="mb-4 text-justify">We do not guarantee that in connection with your use of the Personal Info Protection product offering that we will find your online personal information within any third-party data, or that all data broker websites will be scanned. We do not guarantee that the Services will be effective, or that an opt-out request will be honored or responded to by the relevant data-broker websites. We do not guarantee that an opt-out request will prevent all or any future uses or disclosures of your online personal information by a data broker website, or that we will identify all instances of your online personal information that is eligible for opt-out, or that the data broker websites will not retain copies of your online personal information. Some of the data broker websites may have multiple databases and may acquire and aggregate personal information about individuals on an ongoing basis. The opt-out request we submit on your behalf may not be effective for all sources of online personal information maintained by the data broker websites, or for online personal information acquired by the data broker websites after the opt-out request. In addition, we may not locate all entries or the correct entries of your online personal information that are eligible for opt-out. Not all data broker websites offer the same type of opt-out options. Further, in some instances, even if we are able to effectively submit an opt-out request on your behalf to a data broker website, that data broker website may still maintain your online personal information in its records and may fail to honor or properly respond to an opt-out request. You understand and agree that safecreditscore.com is not responsible for the actions or inactions of any of these data broker sites, and that safecreditscore.com makes no representations, warranties or guarantees related to such data broker sites. You expressly agree that safecreditscore.com will not be liable to you under any circumstances for any actions or inactions of these data broker sites, or for safecreditscore.com's failure for any reason to exercise effective opt-outs on your behalf.</p>

                    <p class="mb-4 text-justify">Not all Services are available with every membership plan. Once you successfully register, you will have immediate access to the registered Services through a personal member portal ("Portal") accessible on and linked through the Website, where you can view your Member Profile as well as the specific Services you have registered with, and any results of such Services. It is the member's responsibility to log into the Portal frequently to use and/or to check the status of any provided Services. We may, at our discretion, modify or discontinue any of the Services or a portion thereof, with or without notice. You agree that we will not be liable to you or any third party for any modification or discontinuance of any of the Services. Your continued use of the Services, or your failure to terminate your membership, after any such modifications have been made to the Services, will constitute your acceptance of those modifications.</p>

                    <h2 class="mb-4" style="font-weight: 700;">REGISTRATION.</h2>

                    <p class="mb-4 text-justify">To access certain areas or features of the Website and to participate in the Services, you will be required to register as a member and to provide certain information about yourself. When you register, you authorize us to create and maintain an account in your name using your account registration information and other information that may be collected about you in accordance with our Privacy Policy as part of providing our Services (collectively, such information is your "Member Profile.")</p>

                    <p class="mb-4 text-justify">To register as a member, you must be a living individual and not a company, corporation or any other entity, you must be eighteen (18) years of age or older and have a valid U.S. Social Security number. You must reside in the contiguous United States while using the Services. Any methods to obscure or hide the country or location of a computer or device along with the use of a VPN, Private or Proxy IP to connect to the Website or use the Services is strictly prohibited. The country listed in your Member Profile must be the country you are both living in, and logging into your member account from. You are only allowed to sign up for yourself, and you agree to provide complete, accurate and current information, and to update this information when it changes. We do not permit any person to sign up for the Services on behalf of another person unless you have an appropriate Power of Attorney. If you provide any information that is untrue or inaccurate, not current, or incomplete, or if we suspect that your information is untrue or inaccurate, not current, or incomplete, we may, in our sole discretion, suspend or terminate your membership and refuse current or future access to the Website or Services. Further, you agree that we will not be liable to you or any third party in the event that we suspend or terminate your access to the Services for any reason. In the event the terms and conditions contained herein these Terms of Use conflict with the terms and conditions of any membership or other agreement you enter into to receive Services, the terms and conditions of such agreement to receive Services will govern and control.</p>

                    <p class="mb-4 text-justify">Should we provide to you, or allow you to create a username and/or password which grants you to access certain parts of the Website and Services, you will be solely responsible for maintaining the confidentiality of the username, password and your account information, and are fully responsible for all activities, including electronic communications, that occur under and on behalf of your account. You agree that you will immediately notify us of any unauthorized use of your password or account, or any other suspected breach of security, and that you will log off of the Website and Services at the end of each session to prevent fraud on your account by third parties. The Website and Services are not intended for use by children under the age of 18. We reserve the right to refuse service, terminate accounts, or remove or edit content in its sole discretion.</p>

                    <h2 class="mb-4" style="font-weight: 700;">SERVICE PROVIDERS.</h2>

                    <p class="mb-4 text-justify">We may use certain third party service providers to provide services or to gather data and authenticate information regarding you, your device, and your accounts. In some instances, this may require you to accept third-party software tools and products through the Services. We do not warrant, endorse, guarantee, or assume any responsibility or liability for any product or service advertised or offered by a third party through the Services or Website. If you use any product or service offered by a third party in conjunction with the Services or Website, you acknowledge and agree that (i) you are responsible for understanding the terms and conditions of your use of the third party product or service; (ii) we do not control the third party or its product or service; (iii) your use of their product or service is at your own risk; and (iv) we are not responsible and may not be held liable for the product or service, or the actions or omissions, of the third party.</p>

                    <h2 class="mb-4" style="font-weight: 700;">INFORMATION AUTHORIZATION.</h2>

                    <p class="mb-4 text-justify">By registering for or otherwise using the Services, you specifically consent to, agree with, and are providing specific "written instructions" in accordance with the Fair Credit Reporting Act and other applicable law, that we, and our respective employees, agents, subsidiaries, affiliates, contractors, and data and service providers, reserve the right to provide your personally identifiable information to, and request, receive and review your consumer credit reports and credit rating, and other information and data about you from and/or through, an authorized bureau (i.e. Equifax, Experian, TransUnion) and affiliated entities. The credit reports and credit rating are intended to furnish you with information that you may not otherwise have readily available to you, but should not be relied upon for important personal and financial decisions. You understand that you are authorizing us and our affiliated companies to obtain such information at any time and use as described in the Terms of Use for as long as Services are provided to you.</p>

                    <p class="mb-4 text-justify">YOU UNDERSTAND THAT IT MAY BE A VIOLATION OF FEDERAL AND/OR STATE LAW FOR YOU TO OBTAIN A CREDIT REPORT ON ANY PERSON OTHER THAN YOURSELF, AND THAT UNDER THE FCRA, ANY PERSON WHO KNOWINGLY AND WILLFULLY OBTAINS INFORMATION ON A CONSUMER FROM A CONSUMER CREDIT REPORTING AGENCY UNDER FALSE PRETENSES SHALL BE FINED UNDER TITLE 18, UNITED STATES CODE, IMPRISONED FOR NOT MORE THAN 2 YEARS, OR BOTH.</p>

                    <p class="mb-4 text-justify">Your registration in the Services may not be fulfilled if we cannot verify your identity or other necessary information. You further understand and agree that we reserve the right to use, store, retain and disclose personal information about you as permitted by law, for our everyday business purposes, such as to maintain your ability to access the Services, to authenticate you when you log in, to send you information about the Services, to perform fraud screening, to verify your identity, to perform collections, to comply with laws, regulations, court orders and lawful instructions from government agencies, to protect the personal safety of subscribers or the public, to defend claims, to resolve disputes, to troubleshoot problems, to enforce these Terms of Use, to protect our rights and property, and to customize, measure, and improve the Services.</p>

                    <p class="mb-4 text-justify"><strong style="text-decoration: underline;">Opt-out Requests.</strong> In order to submit an Opt-out request to remove your information from Data Sites, we may need to interact with Data Sites on your behalf. You expressly authorize us, our agents, services, and employees, to act as your personal representative in order to submit Opt-out requests to Data Sites. You further expressly authorize us to: (a) obtain information on your behalf; (b) submit your personal information to the Data Sites; (c) communicate with the Data Sites or other third parties on your behalf; (d) agree to applicable terms and conditions imposed by these Data Sites; (e) complete and sign or execute documents on your behalf; and (f) take other actions that we believe are reasonably necessary to complete an Opt-out request from a Data Site or to implement the Service.</p>

                    <p class="mb-4 text-justify"><strong style="text-decoration: underline;">Mobile Subscriber Information.</strong> You authorize your wireless carrier to disclose information about your account, such as subscriber status, payment method and device details, if available, to support identity verification, fraud avoidance and other uses in support of transactions for the duration of your business relationship with us. This information may also be shared with other companies to support your transactions with us and for identity verification and fraud avoidance purposes.</p>

                    <h2 class="mb-4" style="font-weight: 700;">FCRA DISCLOSURES.</h2>

                    <p class="mb-4 text-justify">The Fair Credit Reporting Act ("FCRA") allows you to obtain from each national credit reporting agency a disclosure of all the information in your credit file at the time of the request. Full disclosure of information in your file at a credit reporting agency must be obtained directly from such credit reporting agency. The credit reports provided or requested through the Website or Services are not intended to constitute the disclosure of information by a credit reporting agency as required by the Fair Credit Reporting Act or similar laws.</p>

                    <p class="mb-4 text-justify">Under the Fair Credit Reporting Act you are entitled to receive an annual free disclosure of your credit report from each of the national credit reporting agencies (i.e. Experian, Equifax and TransUnion).</p>

                    <p class="mb-4 text-justify">To obtain the free reports, you can:</p>

                    <p class="mb-4 text-justify">- Call 1-877-322-8228;</p>

                    <p class="mb-4 text-justify">- Order online at www.annualcreditreport.com; or</p>

                    <p class="mb-4 text-justify">- Complete the Annual Credit Report Request Form, available at www.ftc.gov/credit, and mail it to: Annual Credit Report Request Service, P.O. Box 105281, Atlanta, GA 30348-5281.</p>

                    <p class="mb-4 text-justify">- You are also entitled to receive a free copy of your credit report from a credit reporting agency if:</p>

                    <p class="mb-4 text-justify">- You have been denied or were otherwise notified of an adverse action related to credit, insurance, employment, or a government granted license or other government granted benefit within the past sixty (60) days based on information in a credit report provided by such agency.</p>

                    <p class="mb-4 text-justify">- You have been denied house/apartment rental or were required to pay a higher deposit than usually required within the past sixty (60) days based on information in a credit report provided by such agency.</p>

                    <p class="mb-4 text-justify">- You certify in writing that you are unemployed and intend to apply for employment during the sixty (60) day period beginning on the date on which you made such certification.</p>

                    <p class="mb-4 text-justify">- You certify in writing that you are a recipient of public welfare assistance.</p>

                    <p class="mb-4 text-justify">- You certify in writing that you have reason to believe that your file at such credit reporting agency contains inaccurate information due to fraud.</p>

                    <p class="mb-4 text-justify">The FCRA also permits consumers to dispute inaccurate information in their credit report without charge. Accurate information cannot be changed. You do not have to purchase your credit report or other information to dispute inaccurate or incomplete information in your credit file maintained by the credit reporting agencies.</p>

                    <p class="mb-4 text-justify">Any Credit Report you request is not intended to constitute the disclosure of information required by the FCRA or similar state laws.</p>

                    <p class="mb-4 text-justify">In addition, if you reside in the state of Colorado, Maine, Maryland, Massachusetts, New Jersey, or Vermont, you are entitled to receive a free copy of your credit report once a year and if you reside in the state of Georgia, you are entitled to receive a free copy of your credit report twice a year. If you are a resident of Mississippi, then beginning in 2016, you are entitled to free credit reports for three (3) years. Otherwise, a consumer reporting agency may impose a reasonable charge for providing you with a copy of your credit report.</p>

                    <h2 class="mb-4" style="font-weight: 700;">SUBSCRIPTIONS; BILLING.</h2>

                    <p class="mb-4 text-justify">By registering as a member, you agree to the product and/or service offer details, including payment for recurring membership subscription fees at the rate and frequency as disclosed at the time of purchase. We will verify your billing information before processing your order.</p>

                    <p class="mb-4 text-justify">When you become a member and subscribe to one of the Services, you understand that it is a membership that automatically renews itself at the agreed upon subscription period (ex: weekly, monthly, yearly, etc) until cancelled or by you. Upon each renewal period, we will automatically charge the then-current membership fee (all applicable taxes and fees included) to the credit card or other payment mechanism that you have authorized or that we have on record for you. If applicable, in the event that your payment or billing source cannot process the membership fee for any reason (such as insufficient credit or funds), we may, at our discretion, re-process the payments owed to the same billing source, or other authorized billing source, in full or in incremental amounts up to 15 times within 30 calendar days from the date of the initial declined payment, in order to process the membership fees. We are not responsible for any overdraft/over-the-limit charges or bank fees triggered by your order being processed or billed. Refunds will not be issued once services have been provided to you. Any reactivation of previously cancelled Services may result in a change to the start of your next membership period and may change the date on which you are billed for each period.</p>

                    <p class="mb-4 text-justify">Consent to obtain personal or credit data to fulfill the benefits of the Services shall be valid under the program for as long as Services are provided to you.</p>

                    <p class="mb-4 text-justify">Not all membership plans and applicable pricing listed on the Website are available for online purchases. We reserve the right to increase or decrease the pricing of our Services from time to time, upon providing you with reasonable notice of the changes to the email you have on file or system generated message within the portal, and you shall have 30 days from the date of such notice to accept or reject such changes. You agree that, unless you cancel your membership prior to the effective date of the price increase, you will be charged the new applicable membership fee at the frequency as agreed to at the time of purchase, and you authorize us to charge the new applicable subscription or membership fee to your payment source. You are solely responsible for any and all fees charged to your payment source by the issuer, bank, or financial institution including, but not limited to, membership, overdraft, insufficient funds and over the credit limit fees. Your continued use of the Services, or your failure to terminate your membership, after any such modifications have been made will constitute your acceptance of those modifications.</p>

                    <h2 class="mb-4" style="font-weight: 700;">CANCELLATION; TERMINATION; REFUND POLICY.</h2>

                    <p class="mb-4 text-justify">You may cancel your membership or subscription at any time by calling us at the toll free number (877) 884-1012 or by using the contact information provided on the Website - OR- by cancelling online in the customer portal, located in the Billing History section of My Account.</p>

                    <p class="mb-4 text-justify">If you cancel your membership or subscription, you will no longer be billed for the Services, however, you will continue to have access to the Services until the end of the subscription or membership period during which you canceled, and until any promotional or bonus period(s) have expired, after which time your access to the Services will cease. No refunds or credits will be issued. We do not provide pro-rated refunds. Memberships can be cancelled at any time, but should be cancelled at least 3 business days prior to your next billing date to avoid future charges.</p>

                    <p class="mb-4 text-justify">We may make inactive, suspend or terminate your membership or your use of this Website or Services at any time, for any reason or for no reason, including without limitation in the event that (a) you breach this Agreement; (b) we are unable to verify or authenticate any information you provide to us; or (c) we believe that your actions may cause financial loss or legal liability for you, our users or us. If you become dissatisfied with the Website, your only recourse is to immediately discontinue use of the Website. Upon cancellation or termination, all rights granted to you will automatically terminate.</p>

                    <h2 class="mb-4" style="font-weight: 700;">ELECTRONIC COMMUNICATIONS.</h2>

                    <p class="mb-4 text-justify">By registering for a subscription or membership, you consent to receive communications from us electronically and agree to be added to our customer email list, as well as our SMS text message customer list. We may communicate with you by email, text message, by posting notices on the Website, by delivering notifications through our mobile applications or through other electronic means. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing. We may send you email newsletters on a variety of topics, and may send you emails on behalf of pre-screened third parties containing promotional offers or opportunities that we believe may be of interest to you. You may start or stop receiving such emails at any time by sending an email to an account that shall be designated for that purpose. Additionally, even if you opt-out of marketing emails, if you are registered or have requested that we contact you about our products or services, you authorize us to send you important notices about the products or services and any pending transactions to any email address you provide to us. It is your duty to keep your email address up to date and to maintain a valid email address and to ensure that emails we send you are not filtered or stopped by spam filters or other types of email blocking functionalities.</p>

                    <h2 class="mb-4" style="font-weight: 700;">WEBSITE LICENSE.</h2>

                    <p class="mb-4 text-justify">As a visitor to the Website and subject to your compliance with these Terms of Use, you are granted a limited, non-exclusive, non-transferable license to access and make personal use of the Website or Services and not to download or modify it, or any portion of it, except with our express written consent. This license does not include any resale or commercial use of the Website or Services, or its contents, or any use of data mining, robots, or similar data gathering and extraction tools, or any derivative use of the Website or Services, or its contents. The Website and Services or any portion thereof, including without limitation the content, text, logos or images, may not be used, reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose, including on any public forum or social media platform, without our express written consent. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) without our express written consent. You may not use any meta tags or any other 'hidden text' utilizing any brand names or trademarks without our express written consent. Any permitted use of the Website or Services does not extend to using the Website or Services for any illegal purpose, or to transmit to or through the Website, or to or through any service, any illegal, harmful, threatening, defamatory, obscene, hateful, pornographic or other objectionable material of any kind, or to interfere with, abuse or otherwise violate the legal rights of any third party using the Website or Services. Any unauthorized or prohibited use of the Website or Services terminates all permissions or licenses granted. We may terminate this license at any time for any reason, whatsoever.</p>

                    <h2 class="mb-4" style="font-weight: 700;">OWNERSHIP.</h2>

                    <p class="mb-4 text-justify">All of the content featured, displayed, included in or made available on the Website or through the Services, including without limitation text, graphics, logos, photographs, button icons, images, moving images, sound, illustrations, data downloads, data compilations and software ("Content"), are owned by us, our licensors, vendors, and/or agents and is protected by United States copyright, trademark and/or patent laws. You may not use, copy, reproduce, publish, upload, post, display, perform, transmit, distribute, modify, license, create derivative works from, transfer or sell any of the Content in any way, including in advertising or publicity pertaining to distribution of materials on this Website, or on any website or social media platform, without our prior written consent. Our trademarks and trade dress may not be used in connection with any other product or service in any manner that is likely to cause confusion among users, or in any manner that disparages or discredits us. All copyrights and trademarks not owned by us that appear on the Website or in the Services are the property of their respective owners. We may own patents that apply to the Services and to the features and services accessible via the Website. Portions of the Services or Website may operate under license of one or more patents.</p>

                    <h2 class="mb-4" style="font-weight: 700;">USER CONTENT LICENSE.</h2>

                    <p class="mb-4 text-justify">By using the Website, uploading or submitting material to or for use on the Website, including but not limited to comments, suggestions or feedback, you grant us a non-exclusive, royalty-free, perpetual, irrevocable, and fully sub-licensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such material throughout the world in any media. You grant us and our sub-licensees the right to use the name that you submit in connection with such material, if we choose. You represent and warrant that you own or otherwise control all of the rights to the material that you submit; that the material is accurate; that use of the material you supply does not violate the Terms of Use and will not cause injury to any person or entity; and that you will indemnify us for all claims arising from the material you supply.</p>

                    <h2 class="mb-4" style="font-weight: 700;">ENDORSEMENTS.</h2>

                    <p class="mb-4 text-justify">We do not endorse any third-party content, including any opinion, recommendation, or advice expressed on or through the Website, and we expressly disclaim any and all liability in connection with any such content. Should you use or rely on such third-party content, data, advertisement, products, goods or services, available or unavailable from, or through any third party, we are not responsible or liable, indirectly or directly, for any damage or loss caused or alleged to be caused by or in connection with such use or reliance and you waive the right to bring or assert any claim against us relating to any interactions or dealings with any third-party and release us from any and all liability for or relating to any interactions or dealings with such third-party.</p>

                    <h2 class="mb-4" style="font-weight: 700;">ACCURACY OF INFORMATION.</h2>

                    <p class="mb-4 text-justify">We attempt to ensure that all information is complete, accurate and current. However, we make no representations or warranties as to the completeness, accuracy, reliability, currency of any information or descriptions of products, services or other content of the Website or Services. Additionally, we reserve the right, for any reason, in our sole discretion, to terminate, suspend or change any aspect of the Website or Services, including but not limited to, content or features. We may impose limits on certain features of the Website or Services or restrict your access to part or all of the Website or Services without notice or penalty.</p>

                    <p class="mb-4 text-justify">Additionally, we reserve the right, for any reason, in our sole discretion, to terminate, suspend or change any aspect of the Website or Services, including but not limited to, content or features. We may impose limits on certain features of the Website or Services or restrict your access to part or all of the Website or Services without notice or penalty.</p>

                    <h2 class="mb-4" style="font-weight: 700;">LINKING TO THIS WEBSITE.</h2>

                    <p class="mb-4 text-justify">Creating or maintaining any link from another website to any page on this Website without our prior written permission is prohibited. Running or displaying this Website or any information or material displayed on this Website in frames or through similar means on another website without our prior written permission is prohibited. Any permitted links to this Website must comply with all applicable laws, rule and regulations.</p>

                    <h2 class="mb-4" style="font-weight: 700;">MONITORING.</h2>

                    <p class="mb-4 text-justify">We have the right but not the obligation to monitor and edit or remove any activity or content. We take no responsibility and assume no liability for any content submitted by you or any third party. During monitoring, information may be examined, recorded, copied, and used for authorized purposes in accordance with our Privacy Policy. Use of the Website constitutes consent to such monitoring. Furthermore, we reserve the right at all times to disclose any content or information posted on any portion of the Website as necessary to satisfy any law, regulation or governmental request, or to refuse to post, or to remove, any content or information, in whole or in part, that in our sole and absolute discretion are objectionable or in violation of this Agreement. Notwithstanding this right, we are not responsible nor liable for any content or information posted or submitted by you.</p>

                    <h2 class="mb-4" style="font-weight: 700;">LINKS.</h2>

                    <p class="mb-4 text-justify">The Website may contain links to websites and/or resources that are not owned, operated or controlled by us or our affiliates. All such links are provided solely as a convenience to you. If you use these links, you will leave this Website. Neither we nor any of our respective affiliates are responsible or liable for the availability of, or any content, materials or other information located on or accessible from any other website. Neither we nor any of our respective affiliates endorse, guarantee, or make any representations or warranties regarding any other websites, or any content, materials or other information located or accessible from any other websites, or the results that you may obtain from using any other websites. If you decide to access any other websites linked to or from this Website, you do so entirely at your own risk.</p>

                    <h2 class="mb-4" style="font-weight: 700;">MINORS.</h2>

                    <p class="mb-4 text-justify">Children under the age of 18 should not and are not authorized to use the Website or Services hereunder. At various places on the Website, we may ask whether users are under the age of 18. We rely on our users to be truthful in responding to these questions. If a user does not identify his/her proper age, we will have no way of verifying actual age with respect to our privacy policy.</p>

                    <h2 class="mb-4" style="font-weight: 700;">CHILD ONLINE PROTECTION ACT NOTIFICATION.</h2>

                    <p class="mb-4 text-justify">Pursuant to 47 U.S.C. Section 230(d) as amended, we hereby notify you that parental control protections (such as computer hardware, software, or filtering services) are commercially available that may assist you in limiting access to material that is harmful to minors. Information identifying current providers of such protections is available from Common Sense (https://www.commonsensemedia.org) and OnGuard Online (http://onguardonline.gov/). Please note that we do not endorse any of the products or services identified on such sites.</p>

                    <h2 class="mb-4" style="font-weight: 700;">ACCESS AND INTERFERENCE.</h2>

                    <p class="mb-4 text-justify">You are responsible for obtaining at your own expense, all equipment and services needed to access and use the Website and Services, including all devices, internet browsers and internet access. If you access the Website or a Website application through a mobile or wireless device, you are responsible for all fees that your carrier may charge you for data, text messaging and other wireless access or communications services.</p>

                    <p class="mb-4 text-justify">You agree that you will not use any robot, spider, scraper or other automated means to access the Website for any purpose without our express written permission. Additionally, you agree that you will not: (i) take any action that imposes, or may impose in our sole discretion an unreasonable or disproportionately large load on our infrastructure; (ii) interfere or attempt to interfere with the proper working of the Website or any activities conducted on the Website; or (iii) bypass any measures we may use to prevent or restrict access to the Website.</p>

                    <h2 class="mb-4" style="font-weight: 700;">FORCE MAJEURE.</h2>

                    <p class="mb-4 text-justify">We shall not be responsible for damages or for delays or failures in performance resulting from acts or occurrences beyond their reasonable control, including, without limitation: fire, lightning, explosion, power surge or failure, water, acts of God, war, revolution, civil commotion or acts of civil or military authorities or public enemies, any law, order, regulation, ordinance, or requirement of any government or legal body or any representative of any such government or legal body, or labor unrest, including without limitation, strikes, slowdowns, picketing, or boycotts, inability to secure raw materials, transportation facilities, fuel or energy shortages, or acts or omissions of other common carriers.</p>

                    <h2 class="mb-4" style="font-weight: 700;">DISCLAIMERS.</h2>

                    <p class="mb-4 text-justify">YOUR USE OF THIS WEBSITE AND THE SERVICES IS AT YOUR RISK. THE CONTENT, FUNCTIONS, INFORMATION, MATERIALS, PRODUCTS AND SERVICES PROVIDED ON OR THROUGH THE WEBSITE AND SERVICES ARE PROVIDED "AS IS" WITHOUT ANY WARRANTIES OF ANY KIND WHATSOEVER, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT OF INTELLECTUAL PROPERTY. NEITHER WE, NOR ANY OF OUR AFFILIATES WARRANT THE ACCURACY OR COMPLETENESS OF THE INFORMATION, MATERIALS OR SERVICES PROVIDED ON OR THROUGH THIS WEBSITE. THE INFORMATION, MATERIALS AND SERVICES PROVIDED ON OR THROUGH THIS WEBSITE MAY BE OUT OF DATE, AND NEITHER WE, NOR ANY OF OUR AFFILIATES MAKES ANY COMMITMENT OR ASSUMES ANY DUTY TO UPDATE SUCH INFORMATION, MATERIALS OR SERVICES.</p>

                    <p class="mb-4 text-justify">WE MAKE NO GUARANTEE THAT THE PRIVACY PROTECT SERVICE WILL FIND A USER'S ONLINE PERSONAL INFORMATION AT ANY OF THE DATA SITES, OR THAT IT WILL SCAN ALL DATA SITES IF A USER'S ONLINE PERSONAL INFORMATION IS NOT PRESENT. WE DO NOT GUARANTEE THAT THE SERVICE WILL BE EFFECTIVE, THAT AN OPT-OUT REQUEST WILL BE HONORED OR RESPONDED TO, OR THAT ALL OPT-OUT REQUESTS FOR A USER'S ONLINE PERSONAL INFORMATION WILL BE EQUIVALENT. WE DO NOT GUARANTEE THAT AN OPT-OUT REQUEST WILL PREVENT ALL OR ANY FUTURE USES OR DISCLOSURES OF A USER'S ONLINE PERSONAL INFORMATION BY A DATA SITE, THAT WE WILL IDENTIFY ALL INSTANCES OF A USER'S ONLINE PERSONAL INFORMATION THAT ARE ELIGIBLE FOR OPT-OUT, OR THAT THE DATA SITES WILL NOT RETAIN COPIES OF A USER'S ONLINE PERSONAL INFORMATION.</p>

                    <h2 class="mb-4" style="font-weight: 700;">LIMITATIONS OF LIABILITY.</h2>

                    <p class="mb-4 text-justify">WE DO NOT WARRANT THAT THE WEBSITE AND SERVICES, ITS SERVERS, OR E-MAIL OR OTHER NOTIFICATIONS SENT BY US ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</p>

                    <p class="mb-4 text-justify">IN NO EVENT WILL WE, OR ANY OF OUR OFFICERS, DIRECTORS, EMPLOYEES, SHAREHOLDERS, AFFILIATES, AGENTS, LICENSEES, SUCCESSORS OR ASSIGNS, NOR ANY PARTY INVOLVED IN THE CREATION, PRODUCTION OR TRANSMISSION OF THIS WEBSITE, BE LIABLE TO YOU OR ANYONE ELSE FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL DAMAGES (INCLUDING, WITHOUT LIMITATION, THOSE RESULTING FROM LOST PROFITS, LOST DATA OR BUSINESS INTERRUPTION) ARISING OUT OF THE USE, INABILITY TO USE, OR THE RESULTS OF USE OF THE WEBSITE AND SERVICES, ANY WEBSITES LINKED TO THE WEBSITE, OR THE MATERIALS, INFORMATION OR SERVICES CONTAINED ON ANY OR ALL SUCH WEBSITE AND SERVICES, WHETHER BASED ON WARRANTY, CONTRACT, TORT OR ANY OTHER LEGAL THEORY AND WHETHER OR NOT ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. YOU SPECIFICALLY ACKNOWLEDGE THAT WE SHALL NOT BE LIABLE FOR USER SUBMISSIONS OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY, AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU. THE FOREGOING LIMITATIONS OF LIABILITY DO NOT APPLY TO THE EXTENT PROHIBITED BY LAW. CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS.</p>

                    <p class="mb-4 text-justify">IN THE EVENT OF ANY PROBLEM WITH THIS WEBSITE OR ANY CONTENT, YOU AGREE THAT YOUR SOLE REMEDY IS TO CEASE USING THIS WEBSITE OR THE SERVICES. IN THE EVENT OF ANY PROBLEM WITH THE PRODUCTS OR SERVICES THAT YOU HAVE PURCHASED ON OR THROUGH THE WEBSITE. TO THE EXTENT PERMITTED BY LAW, YOU AGREE THAT YOUR SOLE REMEDY, IF ANY, IS FROM THE MANUFACTURER OF SUCH PRODUCTS OR SUPPLIER OF SUCH SERVICES, IN ACCORDANCE WITH SUCH MANUFACTURER'S OR SUPPLIER'S WARRANTY, OR TO SEEK A RETURN AND REFUND FOR SUCH PRODUCT OR SERVICES. IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION WHETHER IN CONTRACT OR OTHERWISE EXCEED THE GREATER OF (A) TWENTY FIVE DOLLARS ($25.00) OR (B) THE AMOUNT YOU HAVE PAID FOR SERVICES IN THE PRECEDING SIX (6) MONTHS OF YOUR CLAIM.</p>

                    <h2 class="mb-4" style="font-weight: 700;">INDEMNIFICATION.</h2>

                    <p class="mb-4 text-justify">You agree to defend, indemnify and hold us, our officers, directors, employees, agents, licensees, successors and assigns, and any affiliated company or individual harmless from any and all claims, liabilities, losses, damages, costs, and expenses, including reasonable attorneys' fees, related to or in connection with (i) your breach or violation of any term of this Agreement, including without limitation, your breach of any of the representations and warranties above; (ii) your violation of any third party right, including without limitation any right of privacy, publicity rights or intellectual property rights; (iii) your violation of any law, rule or regulation of the United States or any other country; (iv) any claim for damages that arise as a result of any content that you place or post on the Website; or (v) any other party's access and use of the Website with your unique username, password or other appropriate security code. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and you will not in any event settle or otherwise dispose of any matter without our prior written consent.</p>

                    <h2 class="mb-4" style="font-weight: 700;">DISPUTES; ARBITRATION.</h2>

                    <p class="mb-4 text-justify">EXCEPT AS SET FORTH HEREIN, YOU AGREE THAT YOU ARE WAIVING ALL RIGHTS TO: (A) A TRIAL BY JURY; (B) PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS ACTION ARBITRATION; AND (C) BRING AN ACTION AGAINST US IN A COURT OF LAW. YOU MAY INDIVIDUALLY ARBITRATE ANY CLAIM AGAINST US IN ANY JURISDICTION IN THE UNITED STATES. YOU AGREE THAT ANY DISPUTE RESOLUTION PROCEEDINGS WILL BE CONDUCTED ONLY ON AN INDIVIDUAL BASIS AND NOT IN A CLASS, CONSOLIDATED OR REPRESENTATIVE ACTION.</p>

                    <p class="mb-4 text-justify">Any Claim relating to the use of the Website and Services and/or in your requesting us to contact you about Services, is governed by the laws of the state of Wyoming. A "Claim" is any case, controversy, dispute, tort, disagreement, lawsuit, legal action, or claim now or hereafter pending between you and us, including but not limited to any alleged state or federal statutory violation, or any dispute over the interpretation of the Terms of Use or the arbitrability of any Claim pursuant to the Terms of Use.</p>

                    <p class="mb-4 text-justify">Any Claim now or hereafter pending between you and us relating in any way to your use of the Website or any Services shall be resolved by binding arbitration as described in this section, rather than in court, except that (i) you may assert claims in a small claims court located in the state of Wyoming if your claims qualify and (ii) you or we may bring suit in any state or Federal court in Wyoming, submitting to the jurisdiction of such court and waiving our respective rights to any other jurisdiction, to enjoin infringement or other misuse of intellectual property rights. The parties understand and agree that either party may bring claims against the other only in his/her or its individual capacity and not as a class member in any purported class or representative proceeding. Further, the parties agree that the arbitrator may not consolidate proceedings of more than one person's claims, and may not otherwise preside over any form of representative or class proceeding.</p>

                    <p class="mb-4 text-justify">There is no judge or jury in arbitration, and court review of an arbitration award is limited. However, an arbitrator can award on an individual basis the same damages and relief as a court (including injunctive and declaratory relief or statutory damages), and must follow the provisions of these Terms of Use as a court would. To begin an arbitration proceeding, you must send a letter requesting arbitration and describing your claim to safecreditscore.com, Attn: Business &amp; Legal Affairs; compliance@safecreditscore.com.</p>

                    <h2 class="mb-4" style="font-weight: 700;">GENERAL PROVISIONS.</h2>

                    <p class="mb-4 text-justify">If any provision of these Terms of Use are held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced. You agree that these Terms of Use and all incorporated agreements, including membership and other related client agreements, may be automatically assigned by us in our sole discretion. Headings are for reference purposes only and in no way define, limit, construe or describe the scope or extent of such section. Our failure to act with respect to a breach by you or others does not waive our right to act with respect to subsequent or similar breaches. You agree that any cause of action arising out of or related to the Website, Services or these Terms of Use must commence within one year after the cause of action arose; otherwise, such cause of action is permanently barred. All provisions in these Terms of Use regarding representations and warranties, indemnification, disclaimers, and limitation of liability will survive the termination of this Agreement. If any provision of these Terms of Use are in conflict with any term or condition as set forth in a membership or other client related agreement, the terms and conditions of the membership or client related agreements shall control.</p>

                    <h2 class="mb-4" style="font-weight: 700;">PRIVACY.</h2>

                    <p class="mb-4 text-justify">We may collect, process and transmit certain data obtained from and about you in the course of your accessing the Website or during a phone consultation, including information collected in the course of an abandoned transaction. We maintain the privacy of your information as set forth in our Privacy Policy and we process your personal data in compliance with all relevant laws and codes of practice.</p>

                    <h2 class="mb-4" style="font-weight: 700;">DIGITAL MILLENNIUM COPYRIGHT ACT ("DMCA") NOTICE.</h2>

                    <p class="mb-4 text-justify">In operating the Website, we may act as a "services provider" (as defined by DMCA) and offer services as an online provider of materials and links to third party websites. As a result, third party materials that we do not own or control may be transmitted, stored, accessed or otherwise made available while using the Website. We have in place certain legally mandated procedures regarding allegations of copyright infringement occurring on the Website. We have adopted a policy that provides for the immediate removal of any content or the suspension of any user that is found to have infringed on our rights or of a third party, or that has otherwise violated any intellectual property laws or regulations, or any of the terms and conditions of these Terms of Use. If you believe any material available via the Website or Services infringes, specifically or generally upon a copyright, you should notify us using the notice procedure for claimed infringement under the DMCA (17 U.S.C. Sect. 512(c)(2)). We will respond expeditiously to remove or disable access to the material claimed to be infringing upon said copyright, and will follow the procedures specified in the DMCA to resolve the claim between the notifying party and the alleged infringer who provided the Content. We may give notice to our users of any infringement notice by means of a general notice on any of our websites, electronic mail to a user's e-mail address in our records, or by written communication sent by first-class mail to a user's physical address in our records. If you receive such an infringement notice, you may provide counter-notification in writing to the designated agent that includes the information below. Our designated agent (i.e., proper party for notice) to whom you should address infringement notices under the DMCA is compliance@safecreditscore.com.</p>

                    <h2 class="mb-4" style="font-weight: 700;">SOFTWARE TERMS.</h2>

                    <p class="mb-4 text-justify">The following additional terms apply to any software (including any updates or upgrades to the software and any related documentation) that we make available to you from time to time for your use in connection with the Website and Services (the "Software"):</p>

                    <p class="mb-4 text-justify"><strong>- Use of the Software.</strong> You may use the Software solely for purposes of enabling you to use and enjoy the Website and Services as provided by us, and as permitted by these Terms of Use. You may not incorporate any portion of the Software into your own programs or compile any portion of it in combination with your own programs, transfer it for use with another service, or sell, rent, lease, lend, loan, distribute or sublicense the Software or otherwise assign any rights to the Software in whole or in part. You may not use the Software for any illegal purpose. We may cease providing any Software and we may terminate your right to use any Software at any time. Your rights to use the Software will automatically terminate without notice from us if you fail to comply with any of these Terms of Use. Additional third party terms contained within or distributed with certain Software may apply to that Software (or software incorporated with the Software) and will govern the use of such software in the event of a conflict with these Terms of Use. All Software used in the Website or any Service is our property or of our software suppliers and protected by United States and international copyright laws.</p>

                    <p class="mb-4 text-justify"><strong>- Use of Third Party Services.</strong> When you use the Software, you may also be using the services of one or more third parties, such as a wireless carrier or a mobile platform provider. Your use of these third party services may be subject to the separate policies, terms of use, and fees of these third parties.</p>

                    <p class="mb-4 text-justify"><strong>- No Reverse Engineering.</strong> You may not, and you will not encourage, assist or authorize any other person to copy, modify, reverse engineer, decompile or disassemble, or otherwise tamper with, the Software, whether in whole or in part, or create any derivative works from or of the Software.</p>

                    <p class="mb-4 text-justify"><strong>- Updates.</strong> In order to keep the Software up-to-date, we may offer automatic or manual updates at any time and without notice to you.</p>

                    <p class="mb-4 text-justify"><strong>- Export Regulations; Government End Users.</strong> You must comply with all export and re-export restrictions and regulations of the Department of Commerce and other United States agencies and authorities that may apply to the Software. If you are a U.S. Government end user, we are licensing the Software to you as a "Commercial Item" as that term is defined in the U.S. Code of Federal Regulations (see 48 C.F.R. § 2.101), and the rights we grant you to the Software are the same as the rights we grant to all others under these Terms of Use.</p>

                    <h2 class="mb-4" style="font-weight: 700;">CONTACT INFORMATION.</h2>

                    <p class="mb-4 text-justify">If you do not understand any of the foregoing Terms of Use or if you have any questions or comments, we encourage you to contact us via written correspondence to: info@safecreditscore.com.</p>

                    <h2 class="mb-4" style="font-weight: 700;">NOTICE TO CALIFORNIA RESIDENTS.</h2>

                    <p class="mb-4 text-justify">Under California Civil Codes, California residents are entitled to additional specific consumer rights information. To file a complaint regarding the Services or to receive further information regarding use of the Services, including to cancel your Services, please contact us at safecreditscore.com, 30N South Gould Street Sheridan, WY 82801, or call us toll free at (877) 884-1012, or email us at info@safecreditscore.com. You may also contact the Complaint Assistance Unit of the Division of Consumer Services of the Department of Consumer Affairs in writing at 400 R Street, Suite 1080, Sacramento, California 95814, or by telephone at 916.445.1254 or 800.952.5210.</p>

                </div>
            </div>
        </div>
    </section>
<?php
echo view('site/partials/testimonios', get_defined_vars());
echo view('site/partials/footer', get_defined_vars());
echo view('site/partials/scripts', get_defined_vars()); 
?>